# Generated by Django 3.2 on 2022-01-05 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=30, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fecha_promulgacion', models.DateField(verbose_name='Fecha de Promulgacion')),
                ('reseña', models.TextField(verbose_name='Reseña Ordenanza')),
                ('pdfFile', models.FileField(blank=True, upload_to='ordenanzas/', verbose_name='Archivo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenanzas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('ordenanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenanzas.ordenanza')),
            ],
        ),
    ]
