# Generated by Django 3.2 on 2022-01-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ordenanza',
        ),
        migrations.AddField(
            model_name='ordenanza',
            name='tags',
            field=models.ManyToManyField(to='ordenanzas.Tag', verbose_name='Tags'),
        ),
    ]
