# Generated by Django 3.2 on 2022-01-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenanzas', '0003_auto_20220105_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenanza',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ordenanza',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='ordenanza',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='ordenanza',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenanzas.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
    ]
