# Generated by Django 3.2 on 2022-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenanzas', '0004_auto_20220108_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenanza',
            name='concejal',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='Presentado por'),
        ),
        migrations.AlterField(
            model_name='ordenanza',
            name='tags',
            field=models.ManyToManyField(null=True, to='ordenanzas.Tag', verbose_name='Tags'),
        ),
    ]
